version: "3"
services:
  consumer:
    container_name: consumer
    build:
      context: ./consumer
    networks:
      - kafka_network
    environment:
      KAFKA_BROKER: kafka:9092
  producer:
    container_name: producer
    build:
      context: ./producer
    ports:
      - "3000:3000"
    networks:
      - kafka_network
    environment:
      KAFKA_BROKER: kafka:9092
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 29092:29092
    networks:
      - kafka_network
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "logs:1:1"
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    networks:
      - kafka_network
    ports:
      - "2181:2181"
networks:
  kafka_network:
